version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  app:
    build: .
    container_name: nestjs-app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/reservation-tasks-module
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  mongodb_data: